version: '3.9'
services:
  autoline_mariadb:
    container_name: autoline_mariadb
    build:
      context: ./
      dockerfile: database/Dockerfile
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - autoline_mariadb_data:/var/lib/mysql
    env_file:
      - ../../.env/backend.env
    networks:
      - backend_network
  backend:
    image: backend
    container_name: backend
    depends_on:
      - autoline_mariadb
    ports:
      - '3001:3001'
    env_file:
      - ../../.env/backend.env
    networks:
      - backend_network
      - frontend_network
  frontend:
    image: frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - '8080:80'
      - '443:443'
    env_file:
      - ../../.env/frontend.env
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    networks:
      - backend_network
      - frontend_network

volumes:
  autoline_mariadb_data:
    driver: local
  shared:
    driver: local

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
