version: '3'
services:
  autoline_mariadb:
    container_name: 'autoline_mariadb'
    build:
      context: ./
      dockerfile: database/Dockerfile
    hostname: mariadb
    ports:
      - "3307:3306"
    volumes:
      - autoline_mariadb_data:/var/lib/mysql
    env_file:
      - ../../.env/backend.env

volumes:
  autoline_mariadb_data:
    driver: local
  shared:
    driver: local
