version: '3'
services:
  autoline_mariadb:
    image: mariadb
    container_name: 'autoline_mariadb'
    build:
      context: ./
      dockerfile: database/Dockerfile
    hostname: mariadb
    ports:
      - "3307:3306"
    volumes:
      - autoline_mariadb_data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=autoline"
      - "MYSQL_USER=autoline"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

volumes:
  autoline_mariadb_data:
    driver: local
  shared:
    driver: local
