version: '3.9'
services:
  mariadb:
    container_name: mariadb_local
    build:
      context: ./
      dockerfile: database/Dockerfile
    restart: on-failure
    ports:
      - "3307:3306"
    volumes:
      - mariadb_local:/var/lib/mysql
    env_file:
      - ../../.env/backend.env

volumes:
  mariadb_local:
    driver: local
