version: '3.9'
services:
  autoline_mariadb:
    container_name: autoline_mariadb
    build:
      context: ./
      dockerfile: database/Dockerfile
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - autoline_mariadb_data:/var/lib/mysql
    env_file:
      - ../../.env/backend.env
    networks:
      - backend_network
  backend:
    image: ghcr.io/binarystudioacademy/autoline-backend-dev:latest
    container_name: backend
    depends_on:
      - autoline_mariadb
    ports:
      - '3001:3001'
    env_file:
      - ../../.env/backend.env
    networks:
      - backend_network
      - frontend_network
  frontend:
    image: ghcr.io/binarystudioacademy/autoline-frontend-dev:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ../../.env/frontend.env
#    volumes:
#      - /etc/letsencrypt/live/dev.streamlet.tk/fullchain.pem:/etc/letsencrypt/live/autoline-not-autoria.xyz/fullchain.pem
#      - /etc/letsencrypt/live/dev.streamlet.tk/privkey.pem:/etc/letsencrypt/live/autoline-not-autoria.xyz/privkey.pem
#      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
#      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
#      - ../playback:/assets/segments
    networks:
      - backend_network
      - frontend_network

volumes:
  autoline_mariadb_data:
    driver: local
  shared:
    driver: local

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
