version: "3.8"

# Using `node_modules` mounting pattern described here:
# https://burnedikt.com/dockerized-node-development-and-mounting-node-volumes/#prevent-hosts-node_modules-from-being-mounted

services:
  autoline_mariadb:
    container_name: autoline_mariadb
    build:
      context: ../../
      dockerfile: database/Dockerfile
    restart: on-failure
    ports:
      - "3307:3306"
    networks:
      - autoline_backend_network
    env_file:
      - ../../.env/backend.env
    volumes:
      - autoline_mariadb_data:/var/lib/mysql

  autoline_backend:
    container_name: autoline_backend
    build:
      context: ../../
      dockerfile: backend/Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ../../shared:/shared/
      - exclude_shared:/shared/node_modules/
      - ../../backend:/backend/
      - exclude_backend:/backend/node_modules/
    env_file:
      - ../../.env/backend.env
    environment:
      - FRONTEND_URL=http://autoline_frontend:80
    networks:
      - autoline_backend_network
      - autoline_frontend_network
    depends_on:
      - "autoline_mariadb"

volumes:
  exclude_shared:
  exclude_backend:
  autoline_mariadb_data:
    driver: local

networks:
  autoline_backend_network:
    driver: bridge
  autoline_frontend_network:
    driver: bridge
