version: "3.8"

services:
  autoline_mariadb:
    container_name: autoline_mariadb
    build:
      context: ../../
      dockerfile: database/Dockerfile.dev
    restart: on-failure
    ports:
      - "3307:3306"
    networks:
      - autoline_backend_network
    env_file:
      - ../../.env/backend.env
    volumes:
      - autoline_mariadb_data:/var/lib/mysql

volumes:
  autoline_mariadb_data:
    driver: local

networks:
  autoline_backend_network:
    driver: bridge
