FROM node:16-alpine as shared-builder
COPY package.json yarn.lock tsconfig.json .eslintrc.yml ./
RUN yarn install

COPY .env ./.env

WORKDIR /shared
COPY ./shared/package.json ./shared/yarn.lock ./
RUN yarn install
COPY ./shared ./
RUN yarn build

FROM shared-builder as frontend-builder
COPY --from=shared-builder / ./
WORKDIR /frontend
COPY ./frontend/package.json ./frontend/yarn.lock ./frontend/tsconfig.json ./
RUN yarn install
RUN yarn upgrade @autoline/shared
COPY ./frontend .

EXPOSE 3000
CMD yarn start:dev & cd ../shared && yarn start:dev
