FROM node:16-alpine as shared-builder
COPY package.json yarn.lock tsconfig.json .eslintrc.yml ./
RUN yarn install --immutable --immutable-cache

COPY .env ./.env

WORKDIR /shared
COPY ./shared/package.json ./shared/yarn.lock ./
RUN yarn install --immutable --immutable-cache
COPY ./shared .
RUN yarn build

FROM shared-builder as backend-builder
WORKDIR /backend
COPY ./backend/package.json ./backend/yarn.lock ./backend/tsconfig.json ./
RUN yarn install --immutable --immutable-cache
COPY ./backend .
CMD yarn start:dev & cd ../shared && yarn start:dev
