const {
  VITE_API_ORIGIN_URL,
  VITE_SENTRY_DSN,
  FACEBOOK_APP_ID,
  FACEBOOK_SECRET_KEY,
  VITE_EXCHANGE_RATE_URL,
} = import.meta.env;

const ENV = {
  API_PATH: VITE_API_ORIGIN_URL ?? '',
  SENTRY: {
    DSN: VITE_SENTRY_DSN,
  },

  EXCHANGE_RATE_URL: VITE_EXCHANGE_RATE_URL ?? '',

  FACEBOOK_APP_ID: FACEBOOK_APP_ID,
  FACEBOOK_SECRET_KEY: FACEBOOK_SECRET_KEY,
} as const;

export { ENV };
