export { authRouter } from './auth/auth.router';
export { healthRouter } from './health/health.router';
export { activateRouter } from './activate-mail/activate.router';
export { activateLinkRouter } from './activation-link/activation-link.router';
export { protectedRouter } from './test-protected-route/protected.router';
export { userRouter } from './user/user.router';
export { wishlistRouter } from './preferences/wishlist.router';
export { updateUserRouter } from './update-user/update-user.router';
export { carsRouter } from './cars/cars.router';
