export const carsData = [
  {
    'category_id': 1,
    'cnt': 1651,
    'country_id': 392,
    'eng': 'mazda',
    'marka_id': 47,
    'name': 'Mazda',
    'slang': 'Мазда',
    'value': 47,
    'logo_url': 'https://www.pngall.com/wp-content/uploads/2/Mazda-PNG-Pic.png',
    'models': [
      {
        'category_id': '1',
        'count': 2464,
        'eng': '6',
        'marka_id': 47,
        'model_id': 393,
        'name': '6',
        'description':
          'The Mazda 6 is a good midsize car. It boasts adept handling, responsive steering, and two peppy four-cylinder engine options. It also has an upscale cabin and comes with an abundance of safety tech and infotainment features.',
        'parent_id': 0,
        'slang': '6',
        'value': 393,
        'autoria_body_type_id': 3,
        'year_start': 2002,
        'year_end': null,
        'price_start': 30221,
        'price_end': 42939,
        'photo_urls': [
          'https://www.autocentre.ua/wp-content/uploads/2017/11/2019-Mazda6-23.jpg',
          'https://img.automoto.ua/overview/mazda-6-2020-463-huge-1632.jpg',
        ],
        'complectations': [
          {
            'name': 'TOURING',
            'engine': 'Skyactiv-G-2,0 165 к.с. 6AТ',
            'engine_displacement': 2.0,
            'engine_power': 165,
            'autoria_drivetrain_id': 2,
            'autoria_fuel_type_id': 1,
            'autoria_color_id': 1,
            'autoria_transmission_type_id': 2,
            'price_start': 30221,
            'price_end': null,
            'options': [
              527, 531, 528, 441, 579, 555, 524, 610, 443, 574, 539, 540, 255,
              605, 602, 598, 192, 217, 608, 620, 609,
            ],
          },
          {
            'name': 'PREMIUM',
            'engine': 'Skyactiv-G-2,5 194 к.с. 6AТ',
            'engine_displacement': 2.5,
            'engine_power': 194,
            'autoria_drivetrain_id': 2,
            'autoria_fuel_type_id': 1,
            'autoria_color_id': 1,
            'autoria_transmission_type_id': 2,
            'price_start': 39476,
            'price_end': null,
            'options': [
              527, 531, 528, 441, 579, 555, 524, 610, 443, 574, 539, 540, 255,
              605, 602, 598, 192, 217, 608, 620, 609, 572, 580, 563, 188, 355,
              616,
            ],
          },
        ],
      },
    ],
  },
  {
    'category_id': 1,
    'cnt': 2631,
    'country_id': 392,
    'eng': 'nissan',
    'marka_id': 55,
    'name': 'Nissan',
    'slang': 'Ниссан',
    'value': 55,
    'logo_url':
      'https://upload.wikimedia.org/wikipedia/commons/8/8c/Nissan_logo.png',
    'models': [
      {
        'category_id': '1',
        'count': 7406,
        'eng': 'x-trail',
        'marka_id': 55,
        'model_id': 507,
        'name': 'X-Trail',
        'description':
          'The Nissan X-Trail is a compact crossover SUV (C-segment) produced by the Japanese automaker Nissan since 2000. It was one of Nissans first crossover SUVs and was released about the same time as several other companies car-based crossovers.',
        'parent_id': 0,
        'slang': 'Х-Трейл',
        'value': 507,
        'autoria_body_type_id': 5,
        'year_start': 2001,
        'year_end': null,
        'price_start': 23435,
        'price_end': 26695,
        'photo_urls': [
          'https://www-europe.nissan-cdn.net/content/dam/Nissan/nissan_europe/vehicles/x-trail/2020Update/A-IVI/LHD/2020-nissan-xtrail-Snow-Road-20tdieulhdpace101.jpg.ximg.l_full_m.smart.jpg',
          'https://www-europe.nissan-cdn.net/content/dam/Nissan/nissan_europe/vehicles/x-trail/2_minor_change/eulhd/DESIGN/17tdieulhd-xtrailhelios090.jpg.ximg.l_full_m.smart.jpg',
          'https://www-europe.nissan-cdn.net/content/dam/Nissan/nissan_europe/vehicles/x-trail/2_minor_change/eulhd/DESIGN/17tdieulhd-xtrailhelios013.jpg.ximg.l_full_m.smart.jpg',
        ],
        'complectations': [
          {
            'name': 'VISIA',
            'engine': '2.0l 144 X-Tronic CVT 4WD',
            'engine_displacement': 2.0,
            'engine_power': 144,
            'autoria_drivetrain_id': 1,
            'autoria_fuel_type_id': 1,
            'autoria_color_id': 1,
            'autoria_transmission_type_id': 5,
            'price_start': 23435,
            'price_end': null,
            'options': [217, 459, 621, 137, 441, 604, 611, 579, 605, 560, 539],
          },
          {
            'name': 'ACENTA',
            'engine': '1.6l dCi 130 X-Tronic CVT 2WD',
            'engine_displacement': 1.6,
            'engine_power': 130,
            'autoria_drivetrain_id': 2,
            'autoria_fuel_type_id': 2,
            'autoria_color_id': 1,
            'autoria_transmission_type_id': 5,
            'price_start': 24590,
            'price_end': 26220,
            'options': [
              217, 459, 621, 137, 441, 604, 572, 598, 192, 255, 437, 574, 579,
              605, 560, 539, 582, 555, 556, 486,
            ],
          },
        ],
      },
    ],
  },
];
