export const optionsTypes = [
  {
    'name': 'IsoFix fastening system',
    'value': 621,
    'type': 'security',
    'important': 'false',
  },
  {
    'name': 'Anti-lock braking system (ABS)',
    'value': 217,
    'type': 'auxiliary',
    'important': 'true',
  },
  {
    'name': 'Traction Control (ASR)',
    'value': 606,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Rear door locks',
    'value': 622,
    'type': 'security',
    'important': 'true',
  },
  {
    'name': 'Armored body',
    'value': 515,
    'type': 'security',
    'important': 'false',
  },
  {
    'name': 'Selecting a driving mode',
    'value': 610,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Tire pressure sensor',
    'value': 620,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Interior intrusion sensor (volume sensor)',
    'value': 623,
    'type': 'security',
    'important': 'false',
  },
  {
    'name': 'Driver fatigue sensor',
    'value': 617,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Immobilizer',
    'value': 604,
    'type': 'security',
    'important': 'false',
  },
  {
    'name': 'Lane control',
    'value': 616,
    'type': 'auxiliary',
    'important': 'true',
  },
  {
    'name': 'Lane Departure Warning System',
    'value': 615,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Cruise control',
    'value': 605,
    'type': 'comfort',
    'important': 'true',
  },
  {
    'name': 'Night vision',
    'value': 619,
    'type': 'auxiliary',
    'important': 'true',
  },
  {
    'name': 'Hill descent control system',
    'value': 611,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Hill-start Assist Control',
    'value': 609,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Collision avoidance system',
    'value': 612,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Traffic sign recognition system',
    'value': 618,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Brake Force Distribution (BAS,EBD)',
    'value': 608,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Alarm system',
    'value': 303,
    'type': 'security',
    'important': 'false',
  },
  {
    'name': 'Stabilization System (ESP)',
    'value': 459,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Steering Stabilization (VSM)',
    'value': 607,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Power door locks (central locking)',
    'value': 137,
    'type': 'security',
    'important': 'true',
  },
  {
    'name': 'Autonomous heater webasto',
    'value': 596,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Adaptive Cruise',
    'value': 591,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Cooled Glove box',
    'value': 585,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Board computer',
    'value': 188,
    'type': 'auxiliary',
    'important': 'true',
  },
  {
    'name': 'Fast charging CHAdeMO',
    'value': 597,
    'type': 'multimedia',
    'important': 'false',
  },
  {
    'name': 'Remote engine start',
    'value': 595,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Door closer',
    'value': 587,
    'type': 'comfort',
    'important': 'true',
  },
  {
    'name': 'Starting the engine with a button',
    'value': 525,
    'type': 'comfort',
    'important': 'true',
  },
  {
    'name': 'Multifunction steering wheel',
    'value': 579,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Windscreen heating',
    'value': 589,
    'type': 'comfort',
    'important': 'true',
  },
  {
    'name': 'Steering wheel heating',
    'value': 524,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Hands free trunk opening',
    'value': 582,
    'type': 'comfort',
    'important': 'true',
  },
  {
    'name': 'Pneumatic suspension',
    'value': 592,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Mirror heating',
    'value': 443,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Gearshift paddles',
    'value': 580,
    'type': 'comfort',
    'important': 'true',
  },
  {
    'name': 'Cigarette lighter and ashtray',
    'value': 588,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Projection display',
    'value': 575,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Adjustable pedal assembly',
    'value': 586,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Steering wheel with position memory',
    'value': 577,
    'type': 'comfort',
    'important': 'true',
  },
  {
    'name': 'Seats with massage',
    'value': 581,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Keyless access system',
    'value': 572,
    'type': 'security',
    'important': 'true',
  },
  {
    'name': 'Start/stop system',
    'value': 574,
    'type': 'auxiliary',
    'important': 'true',
  },
  {
    'name': 'Refrigerator',
    'value': 590,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Electronic dashboard',
    'value': 594,
    'type': 'design',
    'important': 'false',
  },
  {
    'name': 'Electric mirror drive',
    'value': 583,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Electric trunk lid actuator',
    'value': 629,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Electric steering wheel adjustment',
    'value': 576,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Electrically folding mirrors',
    'value': 584,
    'type': 'auxiliary',
    'important': 'true',
  },
  {
    'name': 'Android Auto',
    'value': 544,
    'type': 'multimedia',
    'important': 'true',
  },
  {
    'name': 'AUX',
    'value': 538,
    'type': 'multimedia',
    'important': 'false',
  },
  {
    'name': 'Bluetooth',
    'value': 539,
    'type': 'multimedia',
    'important': 'true',
  },
  {
    'name': 'CarPlay',
    'value': 545,
    'type': 'multimedia',
    'important': 'false',
  },
  {
    'name': 'USB',
    'value': 540,
    'type': 'multimedia',
    'important': 'true',
  },
  {
    'name': 'Acoustics',
    'value': 258,
    'type': 'sound',
    'important': 'true',
  },
  {
    'name': 'Audio preparation',
    'value': 534,
    'type': 'sound',
    'important': 'false',
  },
  {
    'name': 'Wireless charger for smartphone',
    'value': 546,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Voice Control',
    'value': 543,
    'type': 'multimedia',
    'important': 'false',
  },
  {
    'name': 'Multimedia system with LCD screen',
    'value': 536,
    'type': 'multimedia',
    'important': 'false',
  },
  {
    'name': 'Navigation system',
    'value': 355,
    'type': 'auxiliary',
    'important': 'true',
  },
  {
    'name': 'Multimedia system for rear passengers',
    'value': 541,
    'type': 'multimedia',
    'important': 'false',
  },
  {
    'name': 'Car on credit',
    'value': 630,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Garage storage',
    'value': 477,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Individual configuration',
    'value': 513,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'First Registration',
    'value': 501,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'First owner',
    'value': 496,
    'type': 'auxiliary',
    'important': 'true',
  },
  {
    'name': 'Manual override for the disabled',
    'value': 502,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Service book',
    'value': 484,
    'type': 'auxiliary',
    'important': 'true',
  },
  {
    'name': 'Rain Sensor',
    'value': 255,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Light sensor',
    'value': 437,
    'type': 'auxiliary',
    'important': 'true',
  },
  {
    'name': 'Daytime running lights',
    'value': 527,
    'type': 'optics',
    'important': 'false',
  },
  {
    'name': 'Headlight washer',
    'value': 441,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Fog lights',
    'value': 528,
    'type': 'optics',
    'important': 'false',
  },
  {
    'name': 'Adaptive lighting system',
    'value': 531,
    'type': 'optics',
    'important': 'true',
  },
  {
    'name': 'High beam control system',
    'value': 532,
    'type': 'optics',
    'important': 'false',
  },
  {
    'name': 'Decorative interior lighting',
    'value': 564,
    'type': 'optics',
    'important': 'false',
  },
  {
    'name': 'Decorative pedal covers',
    'value': 565,
    'type': 'design',
    'important': 'false',
  },
  {
    'name': 'Long base',
    'value': 552,
    'type': 'design',
    'important': 'false',
  },
  {
    'name': 'Crankcase protection',
    'value': 569,
    'type': 'security',
    'important': 'false',
  },
  {
    'name': 'Box protection',
    'value': 570,
    'type': 'security',
    'important': 'true',
  },
  {
    'name': 'Car body MAXI',
    'value': 553,
    'type': 'design',
    'important': 'false',
  },
  {
    'name': 'Luke',
    'value': 132,
    'type': 'design',
    'important': 'false',
  },
  {
    'name': 'Door sills',
    'value': 566,
    'type': 'design',
    'important': 'true',
  },
  {
    'name': 'Steering wheel leather trim',
    'value': 555,
    'type': 'upholstery',
    'important': 'false',
  },
  {
    'name': 'Gearshift lever leather trim',
    'value': 556,
    'type': 'upholstery',
    'important': 'false',
  },
  {
    'name': 'Black ceiling trim',
    'value': 559,
    'type': 'upholstery',
    'important': 'false',
  },
  {
    'name': 'Panoramic roof / Windshield',
    'value': 558,
    'type': 'design',
    'important': 'true',
  },
  {
    'name': 'Front center armrest',
    'value': 560,
    'type': 'design',
    'important': 'false',
  },
  {
    'name': 'Socket 12V',
    'value': 568,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Socket 220V',
    'value': 567,
    'type': 'auxiliary',
    'important': 'false',
  },
  {
    'name': 'Folding table on the backs of the front seats',
    'value': 554,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Folding rear seat',
    'value': 548,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Sunblind on the rear window',
    'value': 631,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Sunblinds in the rear doors',
    'value': 563,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Tinted glass',
    'value': 486,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Third rear head restraint',
    'value': 550,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Third row of seats',
    'value': 551,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Tow bar',
    'value': 571,
    'type': 'design',
    'important': 'false',
  },
  {
    'name': 'Passenger seat back folding function',
    'value': 549,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Rear camera',
    'value': 602,
    'type': 'security',
    'important': 'true',
  },
  {
    'name': 'Camera 360',
    'value': 603,
    'type': 'security',
    'important': 'true',
  },
  {
    'name': 'Rear parking sensors',
    'value': 598,
    'type': 'security',
    'important': 'true',
  },
  {
    'name': 'Front parking sensors',
    'value': 192,
    'type': 'security',
    'important': 'true',
  },
  {
    'name': 'Front camera',
    'value': 601,
    'type': 'security',
    'important': 'true',
  },
  {
    'name': 'Automatic parking system',
    'value': 599,
    'type': 'security',
    'important': 'true',
  },
  {
    'name': 'Side rear',
    'value': 626,
    'type': 'security',
    'important': 'false',
  },
  {
    'name': 'Side front',
    'value': 625,
    'type': 'security',
    'important': 'false',
  },
  {
    'name': 'Driver',
    'value': 211,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': "Driver's knee",
    'value': 628,
    'type': 'comfort',
    'important': 'false',
  },
  {
    'name': 'Car window blinds',
    'value': 627,
    'type': 'comfort',
    'important': 'true',
  },
  {
    'name': 'Passengers',
    'value': 624,
    'type': 'comfort',
    'important': 'false',
  },
];
