name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  lint:
    name: Autoline build test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1.6.0
        with:
          useRollingCache: true
        run: |
          - name: Code Linting
            run: |
              yarn run lint --max-warnings=0

  build-backend:
    name: Autoline build backend.Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build backend Dockerfile
        run: docker build -f .docker/autoline/backend.Dockerfile -t backend .
  build-frontend:
    name: Autoline build frontend.Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build frontend Dockerfile
        run: docker build --build-arg VITE_API_ORIGIN_URL=/api/v1 -f .docker/autoline/frontend.Dockerfile -t frontend .
