name: lint

on:
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Load root dependencies
      uses: bahmutov/npm-install@v1
      with:
        useRollingCache: true

    - name: Load frontend dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: frontend
        useRollingCache: true

    - name: Lint
      run: yarn lint
